-- Generated by Copilot
-- Migration to add RSS scraper columns to jobs table

-- Add source column to track where the job was scraped from
ALTER TABLE jobs ADD COLUMN source TEXT;

-- Add salary_text column to store salary information as text
ALTER TABLE jobs ADD COLUMN salary_text TEXT;

-- Add index for source column for better performance
CREATE INDEX idx_jobs_source ON jobs(source);

-- Update the remote_type enum to include 'fully_remote' option used by RSS scraper
-- First, add the new enum value
ALTER TYPE remote_type ADD VALUE 'fully_remote';

-- Add comment for documentation
COMMENT ON COLUMN jobs.source IS 'Source of the job posting (e.g., RemoteOK, WeWorkRemotely, RSS Feeds)';
COMMENT ON COLUMN jobs.salary_text IS 'Salary information as text (e.g., $50k-70k, Competitive)';
