-- Generated by Copilot
-- Migration to add Google Jobs Search source to existing scraping_sources table
-- Run this in your Supabase SQL editor

-- Add Google Jobs Search source if it doesn't already exist
INSERT INTO scraping_sources (name, url, enabled, description, priority, config)
SELECT 
    'Google Jobs Search',
    'https://www.google.com/search?q=remote+software+developer&ibp=htl;jobs',
    true,
    'Google Jobs search results with advanced scraping (Puppeteer + Structured)',
    'high',
    '{
        "scraper_type": "google_jobs",
        "use_puppeteer": true,
        "use_structured": true,
        "max_pages": 2,
        "max_results": 30,
        "query": "remote software developer",
        "location": "United States"
    }'::jsonb
WHERE NOT EXISTS (
    SELECT 1 FROM scraping_sources 
    WHERE name = 'Google Jobs Search' 
    OR url LIKE '%google.com/search%ibp=htl;jobs%'
);

-- Verify the Google Jobs source was added
SELECT id, name, url, enabled, description, priority, config, created_at 
FROM scraping_sources 
WHERE name = 'Google Jobs Search' OR url LIKE '%google.com/search%ibp=htl;jobs%';

-- Optional: Update existing Google Careers source if it exists to distinguish it
UPDATE scraping_sources 
SET description = 'Google corporate job postings (careers.google.com)'
WHERE name = 'Google Careers' AND url LIKE '%careers.google.com%';

-- Show all scraping sources ordered by priority
SELECT id, name, url, enabled, description, priority 
FROM scraping_sources 
ORDER BY 
    CASE priority 
        WHEN 'high' THEN 1 
        WHEN 'medium' THEN 2 
        WHEN 'low' THEN 3 
        ELSE 4 
    END,
    name;
