// Generated by Copilot
// Test script for the web scraper API
// Usage: node test-scraper.js

const SCRAPER_URL = 'http://localhost:3000/api/scrape'
const CRON_SECRET = 'your-secure-secret-key-here-change-this-in-production'

async function testScraper() {
  console.log('🚀 Testing Web Scraper API...\n')

  try {
    const response = await fetch(SCRAPER_URL, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${CRON_SECRET}`,
        'Content-Type': 'application/json'
      }
    })

    console.log(`📊 Response Status: ${response.status}`)

    if (!response.ok) {
      const error = await response.text()
      console.error('❌ Error:', error)
      return
    }

    const data = await response.json()
    
    console.log('\n✅ Success! Scraper Results:')
    console.log('==========================================')
    console.log(`📈 Total Jobs Found: ${data.summary.totalJobsFound}`)
    console.log(`💾 Total Jobs Inserted: ${data.summary.totalJobsInserted}`)
    console.log(`⚠️  Total Errors: ${data.summary.totalErrors}`)
    
    console.log('\n📋 Source Breakdown:')
    console.log('------------------------------------------')
    
    data.results.forEach(result => {
      console.log(`\n${result.source}:`)
      console.log(`  • Found: ${result.jobsFound} jobs`)
      console.log(`  • Inserted: ${result.jobsInserted} jobs`)
      if (result.errors.length > 0) {
        console.log(`  • Errors: ${result.errors.join(', ')}`)
      }
    })

    console.log('\n📝 Message:', data.message)

  } catch (error) {
    console.error('❌ Network Error:', error.message)
  }
}

// Test unauthorized access
async function testUnauthorized() {
  console.log('\n🔐 Testing Unauthorized Access...')
  
  try {
    const response = await fetch(SCRAPER_URL, {
      method: 'POST',
      headers: {
        'Authorization': 'Bearer wrong-token',
        'Content-Type': 'application/json'
      }
    })

    console.log(`📊 Response Status: ${response.status}`)
    
    if (response.status === 401) {
      console.log('✅ Unauthorized access correctly blocked')
    } else {
      console.log('⚠️  Expected 401, got', response.status)
    }
  } catch (error) {
    console.error('❌ Error testing unauthorized access:', error.message)
  }
}

async function runTests() {
  console.log('🧪 Running Scraper API Tests')
  console.log('========================================\n')
  
  await testUnauthorized()
  await testScraper()
  
  console.log('\n✨ Tests completed!')
}

runTests()
