// Generated by Copilot
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      jobs: {
        Row: {
          id: string
          title: string
          description: string
          company: string
          location: string
          salary_min: number | null
          salary_max: number | null
          employment_type: string
          remote_type: string
          skills: string[]
          posted_at: string
          expires_at: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          description: string
          company: string
          location: string
          salary_min?: number | null
          salary_max?: number | null
          employment_type: string
          remote_type: string
          skills: string[]
          posted_at?: string
          expires_at?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title?: string
          description?: string
          company?: string
          location?: string
          salary_min?: number | null
          salary_max?: number | null
          employment_type?: string
          remote_type?: string
          skills?: string[]
          posted_at?: string
          expires_at?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      job_applications: {
        Row: {
          id: string
          job_id: string
          user_id: string
          status: string
          cover_letter: string | null
          applied_at: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          job_id: string
          user_id: string
          status?: string
          cover_letter?: string | null
          applied_at?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          job_id?: string
          user_id?: string
          status?: string
          cover_letter?: string | null
          applied_at?: string
          created_at?: string
          updated_at?: string
        }
      }
      user_profiles: {
        Row: {
          id: string
          user_id: string
          full_name: string | null
          avatar_url: string | null
          bio: string | null
          skills: string[]
          experience_level: string | null
          location: string | null
          website: string | null
          github_url: string | null
          linkedin_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          full_name?: string | null
          avatar_url?: string | null
          bio?: string | null
          skills?: string[]
          experience_level?: string | null
          location?: string | null
          website?: string | null
          github_url?: string | null
          linkedin_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          full_name?: string | null
          avatar_url?: string | null
          bio?: string | null
          skills?: string[]
          experience_level?: string | null
          location?: string | null
          website?: string | null
          github_url?: string | null
          linkedin_url?: string | null
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      employment_type: 'full-time' | 'part-time' | 'contract' | 'internship'
      remote_type: 'remote' | 'hybrid' | 'on-site'
      application_status: 'pending' | 'reviewing' | 'interview' | 'rejected' | 'accepted'
      experience_level: 'entry' | 'mid' | 'senior' | 'lead' | 'executive'
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
