// Generated by Copilot
import { AuthForm } from '@/components/auth/auth-form'

export default function AuthPage() {
  return (
    <div className="min-h-screen bg-background flex items-center justify-center p-4">
      <div className="w-full max-w-md">
        <div className="text-center mb-8">
          <h1 className="text-2xl font-bold">Remote Job Board</h1>
          <p className="text-muted-foreground">Join thousands of remote job seekers</p>
        </div>
        <AuthForm />
      </div>
    </div>
  )
}
