// Generated by Copilot
// Test page to debug admin settings directly
export default function TestSettings() {
  return (
    <div style={{ padding: '20px', fontFamily: 'monospace' }}>
      <h1>Admin Settings Debug</h1>
      <div id="test-results"></div>
      
      <script dangerouslySetInnerHTML={{
        __html: `
          async function testSettings() {
            const resultsDiv = document.getElementById('test-results');
            resultsDiv.innerHTML = '<p>Testing admin settings...</p>';
            
            try {
              // Test settings API
              const response = await fetch('/api/admin/settings');
              const data = await response.json();
              
              resultsDiv.innerHTML = \`
                <h3>Settings API Response:</h3>
                <p>Status: \${response.status}</p>
                <pre>\${JSON.stringify(data, null, 2)}</pre>
                
                <h3>Analysis:</h3>
                <p>Success: \${data.success ? 'Yes' : 'No'}</p>
                <p>Sources count: \${data.settings?.sources?.length || 0}</p>
                <p>Sources:</p>
                <ul>
                  \${data.settings?.sources?.map(s => \`<li>\${s.name}: \${s.url}</li>\`).join('') || '<li>No sources found</li>'}
                </ul>
              \`;
            } catch (error) {
              resultsDiv.innerHTML = \`<p>Error: \${error.message}</p>\`;
            }
          }
          
          // Auto-run test
          testSettings();
        `
      }} />
    </div>
  );
}
