// Generated by Copilot
'use client'

import { useState } from 'react'
import { Card, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Search } from 'lucide-react'
import { useRouter } from 'next/navigation'

export function QuickSearch() {
  const [searchTerm, setSearchTerm] = useState('')
  const router = useRouter()

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault()
    if (searchTerm.trim()) {
      router.push(`/search?title=${encodeURIComponent(searchTerm.trim())}`)
    }
  }

  return (
    <Card>
      <CardContent className="p-6">
        <form onSubmit={handleSearch} className="flex gap-4">
          <div className="flex-1">
            <Input
              placeholder="Search jobs by title, skills, or keywords..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="text-lg h-12"
            />
          </div>
          <Button type="submit" size="lg" className="px-8 flex items-center gap-2">
            <Search className="h-5 w-5" />
            Search
          </Button>
        </form>
        <div className="mt-4 text-center">
          <Button variant="link" onClick={() => router.push('/search')}>
            Advanced Search Options
          </Button>
        </div>
      </CardContent>
    </Card>
  )
}
