// Generated by Copilot
import { Button, Card, CardContent, CardDescription, CardHeader, CardTitle, Input, Label, Tag } from '@/components/ui';

export default function Home() {
  return (
    <div className="min-h-screen bg-background p-8">
      <div className="max-w-4xl mx-auto space-y-8">
        <div className="text-center space-y-4">
          <h1 className="text-4xl font-bold text-foreground">Remote Job Board MVP</h1>
          <p className="text-lg text-muted-foreground">
            A modern job board built with Next.js 14, TypeScript, and Tailwind CSS
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <Card>
            <CardHeader>
              <CardTitle>Senior Frontend Developer</CardTitle>
              <CardDescription>Remote • Full-time • $80k-$120k</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <p className="text-sm text-muted-foreground">
                We&apos;re looking for an experienced frontend developer to join our remote team...
              </p>
              <div className="flex flex-wrap gap-2">
                <Tag>React</Tag>
                <Tag variant="secondary">TypeScript</Tag>
                <Tag variant="outline">Next.js</Tag>
              </div>
              <Button className="w-full">Apply Now</Button>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>UI/UX Designer</CardTitle>
              <CardDescription>Remote • Contract • $60k-$90k</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <p className="text-sm text-muted-foreground">
                Join our design team to create beautiful and intuitive user experiences...
              </p>
              <div className="flex flex-wrap gap-2">
                <Tag>Figma</Tag>
                <Tag variant="secondary">Adobe Creative Suite</Tag>
                <Tag variant="outline">Prototyping</Tag>
              </div>
              <Button variant="outline" className="w-full">Learn More</Button>
            </CardContent>
          </Card>
        </div>

        <Card>
          <CardHeader>
            <CardTitle>Search Jobs</CardTitle>
            <CardDescription>Find your next remote opportunity</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div className="space-y-2">
                <Label htmlFor="job-title">Job Title</Label>
                <Input id="job-title" placeholder="e.g. Frontend Developer" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="location">Location</Label>
                <Input id="location" placeholder="e.g. Remote, San Francisco" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="salary">Salary Range</Label>
                <Input id="salary" placeholder="e.g. $80k-$120k" />
              </div>
            </div>
            <div className="flex gap-2">
              <Button>Search Jobs</Button>
              <Button variant="outline">Clear Filters</Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
