// Generated by Copilot
'use client'

import { useState } from 'react'
import { useUser, useJobSearch } from '@/lib\supabase\hooks'
import { UserMenu } from '@/components/auth/user-menu'
import { JobList } from '@/components/jobs/job-list'
import { JobSearch } from '@/components/jobs/job-search'
import { Button } from '@/components/ui/button'
import Link from 'next/link'

export default function Home() {
  const { user, loading } = useUser()
  const { jobs, loading: searchLoading, error, totalCount, pagination, searchJobs } = useJobSearch()
  const [isSearchMode, setIsSearchMode] = useState(false)
  const [currentSearchParams, setCurrentSearchParams] = useState<any>({})

  // Handle search functionality
  const handleSearch = (filters: any) => {
    const searchParams = {
      title: filters.title || undefined,
      location: filters.location || undefined,
      employmentType: filters.employmentType || undefined,
      salaryMin: filters.salaryMin ? parseInt(filters.salaryMin) : undefined,
      salaryMax: filters.salaryMax ? parseInt(filters.salaryMax) : undefined,
      page: 1
    }
    
    setCurrentSearchParams(searchParams)
    setIsSearchMode(true)
    searchJobs(searchParams)
  }

  // Handle search clear
  const handleClearSearch = () => {
    setIsSearchMode(false)
    setCurrentSearchParams({})
  }

  // Handle pagination for search results
  const handlePageChange = (page: number) => {
    const newSearchParams = { ...currentSearchParams, page }
    setCurrentSearchParams(newSearchParams)
    searchJobs(newSearchParams)
  }

  return (
    <div className="min-h-screen bg-background p-8">
      <div className="max-w-6xl mx-auto space-y-8">
        <div className="flex items-center justify-between">
          <div className="space-y-4">
            <h1 className="text-4xl font-bold text-foreground">Remote Job Board MVP</h1>
            <p className="text-lg text-muted-foreground">
              Find your next remote opportunity with Supabase integration
            </p>
          </div>
          <div className="flex items-center gap-4">
            {loading ? (
              <div className="h-8 w-24 bg-muted animate-pulse rounded"></div>
            ) : user ? (
              <UserMenu />
            ) : (
              <Link href="/auth">
                <Button>Sign In</Button>
              </Link>
            )}
          </div>
        </div>

        {/* Search Section */}
        <Card>
          <CardHeader>
            <CardTitle>Search Jobs</CardTitle>
            <CardDescription>Find your next remote opportunity</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div className="space-y-2">
                <Label htmlFor="job-title">Job Title</Label>
                <Input id="job-title" placeholder="e.g. Frontend Developer" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="location">Location</Label>
                <Input id="location" placeholder="e.g. Remote, San Francisco" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="salary">Salary Range</Label>
                <Input id="salary" placeholder="e.g. $80k-$120k" />
              </div>
            </div>
            <div className="flex gap-2">
              <Button>Search Jobs</Button>
              <Button variant="outline">Clear Filters</Button>
            </div>
          </CardContent>
        </Card>

        {/* Jobs Section */}
        <div className="space-y-6">
          <div className="flex items-center justify-between">
            <h2 className="text-2xl font-bold">Latest Jobs</h2>
            {user && (
              <Button variant="outline">Post a Job</Button>
            )}
          </div>
          <JobList />
        </div>
      </div>
    </div>
  )
}