// Generated by Copilot
'use client'

import RSSScrapingSettings from '../admin/dashboard/components/RSSScrapingSettings'

export default function TestRSSPage() {
  return (
    <div className="min-h-screen bg-gray-50 p-8">
      <div className="max-w-6xl mx-auto">
        <h1 className="text-2xl font-bold mb-8">RSS Scraping Settings Test</h1>
        <RSSScrapingSettings />
      </div>
    </div>
  )
}
