// Generated by Copilot
'use client'

import { useUser, useSupabase } from '@/lib/supabase/hooks'
import { useAdmin } from '@/lib/supabase/admin-hooks'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import Link from 'next/link'

export function UserMenu() {
  const { user, loading } = useUser()
  const { isAdmin } = useAdmin()
  const supabase = useSupabase()

  const handleSignOut = async () => {
    await supabase.auth.signOut()
  }

  if (loading) {
    return (
      <div className="flex items-center space-x-2">
        <div className="h-8 w-16 bg-muted animate-pulse rounded"></div>
      </div>
    )
  }

  if (!user) {
    return null
  }

  return (
    <Card className="w-fit">
      <CardContent className="p-4">
        <div className="flex items-center space-x-4">
          <div className="flex flex-col">
            <span className="text-sm font-medium">{user.email}</span>
            {user.user_metadata?.full_name && (
              <span className="text-xs text-muted-foreground">
                {user.user_metadata.full_name}
              </span>
            )}
            {isAdmin && (
              <span className="text-xs text-blue-600 font-medium">Admin</span>
            )}
          </div>
          <div className="flex flex-col space-y-2">
            {isAdmin && (
              <Link href="/admin/review">
                <Button variant="outline" size="sm" className="text-xs">
                  Admin Panel
                </Button>
              </Link>
            )}
            <Button variant="outline" size="sm" onClick={handleSignOut}>
              Sign Out
            </Button>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}
